sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: LiuProject
    username: root
    password: 12345678


  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:


  redis:
    host: localhost
    port: 6379
    password: 12345678

  wechat:
    secret: 7c8024c0b66c3e8f8453c92d216635b4
    appid: wxe4cd82d7cb0652fa
